#include <vector>
#include <list>
#include <map>
#include <set>
#include <queue>
#include <deque>
#include <stack>
#include <bitset>
#include <algorithm>
#include <functional>
#include <numeric>
#include <utility>
#include <sstream>
#include <iostream>
#include <iomanip>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <ctime>

using namespace std;


class LongWordsDiv2 {
   public:
      string find(string w) {
         for(int i=0;i<w.size();++i)
            if((w[i]<'A')||(w[i]>'Z'))
               return "Dislikes";
         for(int i=1;i<w.size();++i)
            if(w[i]==w[i-1])
               return "Dislikes";
         for(int i='A';i<='Z';++i)
            for(int j='A';j<='Z';++j){
               vector< char > tmp;
               tmp.push_back(i);
               tmp.push_back(j);
               tmp.push_back(i);
               tmp.push_back(j);
               for(int k=w.size()-1;k>=0;--k){
                  if(w[k]==*tmp.rbegin()){
                     tmp.pop_back();
                     if(tmp.empty())
                        return "Dislikes";
                  }
               }
            }
         return "Likes";
      }
};


// BEGIN KAWIGIEDIT TESTING
// Generated by KawigiEdit 2.1.4 (beta) modified by pivanof
bool KawigiEdit_RunTest(int testNum, string p0, bool hasAnswer, string p1) {
   cout << "Test " << testNum << ": [" << "\"" << p0 << "\"";
   cout << "]" << endl;
   LongWordsDiv2 *obj;
   string answer;
   obj = new LongWordsDiv2();
   clock_t startTime = clock();
   answer = obj->find(p0);
   clock_t endTime = clock();
   delete obj;
   bool res;
   res = true;
   cout << "Time: " << double(endTime - startTime) / CLOCKS_PER_SEC << " seconds" << endl;
   if (hasAnswer) {
      cout << "Desired answer:" << endl;
      cout << "\t" << "\"" << p1 << "\"" << endl;
   }
   cout << "Your answer:" << endl;
   cout << "\t" << "\"" << answer << "\"" << endl;
   if (hasAnswer) {
      res = answer == p1;
   }
   if (!res) {
      cout << "DOESN'T MATCH!!!!" << endl;
   } else if (double(endTime - startTime) / CLOCKS_PER_SEC >= 2) {
      cout << "FAIL the timeout" << endl;
      res = false;
   } else if (hasAnswer) {
      cout << "Match :-)" << endl;
   } else {
      cout << "OK, but is it right?" << endl;
   }
   cout << "" << endl;
   return res;
}
int main() {
   bool all_right;
   all_right = true;

   string p0;
   string p1;

   {
      // ----- test 0 -----
      p0 = "AAA";
      p1 = "Dislikes";
      all_right = KawigiEdit_RunTest(0, p0, true, p1) && all_right;
      // ------------------
   }

   {
      // ----- test 1 -----
      p0 = "ABCBA";
      p1 = "Likes";
      all_right = KawigiEdit_RunTest(1, p0, true, p1) && all_right;
      // ------------------
   }

   {
      // ----- test 2 -----
      p0 = "ABCBAC";
      p1 = "Dislikes";
      all_right = KawigiEdit_RunTest(2, p0, true, p1) && all_right;
      // ------------------
   }

   {
      // ----- test 3 -----
      p0 = "TOPCODER";
      p1 = "Likes";
      all_right = KawigiEdit_RunTest(3, p0, true, p1) && all_right;
      // ------------------
   }

   {
      // ----- test 4 -----
      p0 = "VAMOSGIMNASIA";
      p1 = "Dislikes";
      all_right = KawigiEdit_RunTest(4, p0, true, p1) && all_right;
      // ------------------
   }

   {
      // ----- test 5 -----
      p0 = "SINGLEROUNDMATCH";
      p1 = "Likes";
      all_right = KawigiEdit_RunTest(5, p0, true, p1) && all_right;
      // ------------------
   }

   {
      // ----- test 6 -----
      p0 = "DALELOBO";
      p1 = "Likes";
      all_right = KawigiEdit_RunTest(6, p0, true, p1) && all_right;
      // ------------------
   }

   if (all_right) {
      cout << "You're a stud (at least on the example cases)!" << endl;
   } else {
      cout << "Some of the test cases had errors." << endl;
   }
   return 0;
}
// END KAWIGIEDIT TESTING
//Powered by KawigiEdit 2.1.4 (beta) modified by pivanof!
